[package]
name = "tutorlolv2_avif"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.8"
ravif = { version = "0.12.0", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.149"
tokio = "1.49.0"
