[package]
name = "tutorlolv2_macros"
version = "0.1.6"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
tutorlolv2_fmt = { path = "../tutorlolv2_fmt" }
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
serde_json = "1"
