[package]
name = "tutorlolv2_gen"
version = "0.1.3"
edition = "2024"

[dependencies]
tutorlolv2_types = { workspace = true }
bincode = { version = "2.0.1", default-features = false, features = ["derive"] }
paste = "1.0.15"
phf = { version = "0.13.1", features = ["macros"] }
serde = { version = "1.0", features = ["derive"] }
const_sized_bit_set = "0.3.0"
